### ISSUE TITLE
where in the template hierarchy to place grid-container divs?

### ISSUE THREAD

**Issue by mdlincoln** [dSHARP-CMU/cmesh_theme#38]
I've been looking over the latest updates to the themes from last week. Thank you! I have a question about a common pattern that shows up in the themes. Right now in base.html this is the immediate wrapper around the `body` block:

```html
<main class="cmp-main-content">
  {% block body %}{% endblock body %}
</main>
```

In most (all?) of the templates that you've modified to inherit from this new base, they start the body block like so:

```html
{% block body %}
<div class="grid-container">
  <section id="content">
     <!-- More html -->
  </section>
</div>
{% endblock body %}
```

Much of the missing margin things like https://github.com/dSHARP-CMU/cmesh_theme/pull/36 that we've been stomping out have to do with adding those `grid-container` divs in. Would it make sense to put those recurring pieces into base.html instead? That way anything inheriting from base.html (i.e. most of the templates you've had to modify) would end up wrapped inside there? Are there any things that inherit from base.html that _should not_ have that `grid-container` div around them?

**Comment by pfulton** [comment]
I agree: having that "main" `.grid-container` sprinkled amongst the different templates is not very DRY.

If we were to move it back to the `base` file, the only place (currently) where things would break would be in [templates/journal/index.html](https://github.com/dSHARP-CMU/cmesh_theme/blob/027110507dd42a253003307145d3fccd0f9c8e3a/templates/journal/index.html#L19).

Would it be possible to create a block for the chunk of code from lines 20 - 48 in that template, and reference it inside the body block? If so, I think we could move that `.grid-container` div back to the `base` file, and wrap it around the body block call.

---

Also, for additional reference, `.grid-container` is a Foundation grid class. [Here's some info on it](https://foundation.zurb.com/sites/docs/xy-grid.html#grid-container). It's the class that centers and constrains things within a Zurb grid.

**Comment by mdlincoln** [comment]
@pfulton I think that should be possible. I'll do some poking around today. In addition to DRY-ing out the theme, it'll also resolve a whole bunch of remaining margin problems on some forms pages etc.

**Comment by mdlincoln** [comment]
Would it also make sense to move the `<section class="container">` tags into base.html as well? They appear to go hand-in-hand with `.grid-container`?

**Comment by mdlincoln** [comment]
disregard above - I see now why the section tags are where they are!
